version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog
    ports:
      - "${SMTP_PORT}:1025"
      - "${HTTP_PORT}:8025"
    restart: always
    networks:
      - default
    container_name: dde-mailhog
networks:
  default:
    name: dde
    external: true
