x-extra_hosts:
  &extra-hosts
  - 'example.test:172.17.0.1'

x-volumes:
  &default-volumes
  - &php-ini ./config/php/php.ini:/usr/local/etc/php/conf.d/zz-php.ini
  - &opcache-ini ./config/php/opcache.ini:/usr/local/etc/php/conf.d/zz-opcache.ini
  - &xdebug-ini ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini
  - &php-fpm-ini ./config/php/php-fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
  - &composer /usr/local/bin/composer:/usr/local/bin/composer
  - &composer-cache ${COMPOSER_HOME}:/var/www/.composer:cached
  - &www ${WWW_DIR}:/var/www/html

x-service:
  &default-service
  restart: always
  networks:
    - default
  privileged: true

x-php_service:
  &php-service
  << : *default-service
  expose:
    - "9000"
  environment:
    TZ: ${TZ}
    COMPOSER_HOME: /var/www/.composer
    PHP_IDE_CONFIG: serverName=laravel
  extra_hosts: *extra-hosts

services:
  php83:
    << : *php-service
    build:
      context: ../dockerfiles
      dockerfile: ./php8/Dockerfile
      args:
        PHP_VERSION: ${PHP8_VERSION}
        SOURCES_MIRRORS: ${SOURCES_MIRRORS}
    image: ${PHP8_IMAGE}
    volumes:
      - *php-ini
      - *opcache-ini
      - *xdebug-ini
      - *php-fpm-ini
      - *composer
      - *composer-cache
      - *www
      - ../logs/laravel/php83:/var/log/php
    container_name: laravel-php83

  nginx:
    << : *default-service
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_PORT}:80"
      - 443:443
    volumes:
      - *www
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ../logs/laravel/nginx:/var/log/nginx
    environment:
      TZ: ${TZ}
    container_name: laravel-nginx
    depends_on:
      - php83

networks:
  default:
    name: dde
    external: true
