services:
  gitlab:
    image: $GITLAB_IMAGE
    restart: always
    hostname: $GITLAB_HOSTNAME
    environment:
      TZ: $TZ
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = $SSH_PORT
        gitlab_rails['backup_keep_time'] = $BACKUP_KEEP_TIME
    ports:
      - '$HTTP_PORT:80'
      - '$HTTPS_PORT:443'
      - '$SSH_PORT:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    container_name: dde-gitlab
networks:
  default:
    name: dde
    external: true
