version: "3.8"
services:
    db:
        image: mysql:${MYSQL_VERSION}
        ports:
            - "${MYSQL_PORT}:3306"
        volumes:
            - data:/var/lib/mysql
            # - ./mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
            # - ../log/mysql/err.log:/var/lib/mysql/err.log
            # - ../log/mysql/mysql-slow.log:/var/lib/mysql/mysql-slow.log
        environment:
            TZ: ${TZ}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        command:
            --default-authentication-plugin=mysql_native_password
        restart: always
        networks:
            - default
        container_name: mysql
networks:
    default:
volumes:
    data:
