services:
  db:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_DIR}:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:rw
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --transaction-isolation=READ-COMMITTED
      --explicit_defaults_for_timestamp=1
      --max_connections=100
      --innodb_buffer_pool_size=512M
      --innodb_log_file_size=256M
      --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    restart: always
    networks:
      - default
    container_name: dde-mysql
networks:
  default:
    name: dde
    external: true
volumes:
  data:
