services:
  db:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_DIR}:/var/lib/mysql
      # 使用数据卷, 把下一行的注释去掉，把上一行注释掉
      # - data:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:rw
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    networks:
      - default
    container_name: dde-mysql
networks:
  default:
    name: dde
    external: true
volumes:
  data:
